pipeline {
    agent {
        docker {
            image 'node' 
            args '-p 3000:3000' 
        }
    }
    environment { 
        CI = 'true'
    }
    stages {
        stage('Build') { 
            steps {
                sh 'npm install'
                sh 'npm build'
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
                input message: 'Finished using the web site? (Click "Proceed" to continue)' 
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Deploy') { 
            steps {
                sshagent(['my SSH']) {
                    echo 'this works...'
                    sh 'scp -o StrictHostKeyChecking=no -r dist/* deviceappstore.com:/var/www/nuofa.co/static/'
                }
            }
        }
    }
}
